### ISSUE TITLE
Features branch broken

### ISSUE THREAD

**Issue by usernametaken273** [slow/show-hidden-channels#4]
No hidden channels are showing up on the features branch (kernel + pc-compat)

````
[Powercord:Patcher] Could not fire after patch for default of shc-navigable-channels TypeError: getMutableGuildChannels is not a function
    at ShowHiddenChannels.getHiddenChannels (kernel\\packages\\pc-compat\\plugins\\show-hidden-channels\\index.jsx:442)
````
Appears to have just been broken sometime today (2022-03-29)

Performance branch still working currently, and shows all channels

**Comment by BlackOfWorld** [comment]
As of today (4th of May), discord pushed update where even performance branch got borked.

**Comment by marioparaschiv** [comment]
> els (kernel\\packages\\pc

Fixed. However, I don't feel like fixing features branch as its incredibly slow and has a huge performance impact as its a 1:1 port of DevilBro's show hidden channels. Please use the performance branch.

**Comment by marioparaschiv** [comment]
That being said, anyone is welcome to open a PR fixing the features branch.
