### ISSUE TITLE
[Canary] Showing "permanent" notifications

### ISSUE THREAD

**Issue by RzR332Guyver** [slow/show-hidden-channels#6]
For some reason, when I mark channels as read, the notifications prompt will stay.

Even after disabling the plugin, marking the channels/folders as read, and then re-enabling the notifications will return.
https://cdn.discordapp.com/attachments/861733346539077633/1015018499531354262/unknown.png
https://cdn.discordapp.com/attachments/861733346539077633/1015018499724296315/unknown.png
Images to show what I mean

**Comment by FintasticMan** [comment]
I'm experiencing this as well on the stable Discord channel.

**Comment by asportnoy** [comment]
Can reproduce as well. Reloading Discord clears it temporarily, I'm assuming until there's a new unread message in the hidden channel.

**Comment by ghost** [comment]
I can also confirm it is the case on the stable client.

**Comment by sapphonie** [comment]
can repro

**Comment by Sightem** [comment]
can reproduce
