### ISSUE TITLE
I bid thee farewell...

### ISSUE THREAD

**Issue by plexede** [slow/show-hidden-channels#7]
One of of the best.
Will it be distributed externally like the other banned addons? Or discontinued altogether...

**Comment by centuryt** [comment]
fuck better discord and wtf is going on? policies? wtf are those? just let me use my damn plugin
its one of the most important plugins

**Comment by whyrmph** [comment]
absolutely agree
return the plugin!!!!

**Comment by hydino2085143** [comment]
Does anyone know where to find a copy of ShowHiddenChannels? I'm fine with BD enforcing policies on their own plugin/themes marketplace but having all copies wiped from the internet is a shame.

**Comment by centuryt** [comment]
> Does anyone know where to find a copy of ShowHiddenChannels? I'm fine with BD enforcing policies on their own plugin/themes marketplace but having all copies wiped from the internet is a shame.

anyone who needs an older version can message me on telegram @centuryt91

**Comment by hydino2085143** [comment]
Old versions won't work, it will auto-update to the borked version or spam the console with errors.

**Comment by hydino2085143** [comment]
https://github.com/JustOptimize/return-seeHiddenMessages this repo seems promising, it also includes an un-borked version of 0BDFDB

**Comment by asportnoy** [comment]
You guys realize that this is the Powercord/Replugged plugin, not the BetterDiscord one, right?
![Screenshot on 2022-09-05 at 10 45 57](https://user-images.githubusercontent.com/14863373/188484238-182501fb-d534-408f-960b-448e8b9f192f.png)

**Comment by nyakowint** [comment]
bd users arent exactly known for being smart you know :trollface: 

https://user-images.githubusercontent.com/24845294/188488098-a6041134-ca03-4a80-933b-7304c16d7ad1.mp4

**Comment by skullbite** [comment]
smartest bd user

**Comment by plexede** [comment]
> You guys realize that this is the Powercord/Replugged plugin, not the BetterDiscord one, right? ![Screenshot on 2022-09-05 at 10 45 57](https://user-images.githubusercontent.com/14863373/188484238-182501fb-d534-408f-960b-448e8b9f192f.png)

it linked to this repo for some reason

**Comment by resucutie** [comment]
i feel that i should make show hidden channels just because ppl rly care to see hidden porn channels that they can't even access

*tip: i was being ironic. you guys are too stupid to deserve such plugin*

**Comment by Bluscream** [comment]
I like this issue

**Comment by plexede** [comment]
> i feel that i should make show hidden channels just because ppl rly care to see hidden porn channels that they can't even access
> 
> _tip: i was being ironic. you guys are too stupid to deserve such plugin_

i only ever used it to bother mods (jokingly, were all friends)
you want the truth? i was lying. this isnt "one of the best," i was only giving a compliment

**Comment by nyakowint** [comment]
ok
