### ISSUE TITLE
[Suggestion] Porting and Cooperation

### ISSUE THREAD

**Issue by phoriah** [slow/show-hidden-channels#9]
There is currently a group of people bring back BD's SHC to life ever since it was nuked.
[here](https://github.com/Saalvage/BetterDiscordAddons)
They also have their own Discord and Subreddit dedicated to all of this (you can find it on opened issue there)
All I'm saying is if you could potentially team up with them for possible port of this repo as it seems like the ideal solution (yours)
Or simply share your knowledge and possible help : )
Just a suggestion!
Thanks, P.

**Comment by marioparaschiv** [comment]
https://github.com/discord-modifications/better-discord-plugins/blob/master/ShowHiddenChannels
